### PR TITLE
Enhancement: Map in compose + map-overlay

### PR DESCRIPTION
**Pull request by MarcelReiter**
This PR implements a map overlay for webcams.
While implementing that, i noticed there's finally a native compose maps integration, which made things much easier.
So i scrapped the implementation i had started, switched maps to compose and then 🚀 

This PR still has some rough edges, therefore it's a draft:
- The overlay initially is unconstrained high, and then resizes to wrap-content as expected??
- the enter / exit animations of the overlay are weird
- webcams id isn't displayed

### CODE REVIEW

**Comment by MarcelReiter** [comment]
Please note:
- the api seems to only provide roadworks in the moment, no webcams.
- Therefore it was massively difficult to test webcams :/

**Comment by tscholze** [comment]
@MarcelReiter if there are only roadworks, the webcam endpoint seems to be changed - at the point writing the API everything worked.

Please do not hasitate to inform me about something and not waste your precious time in mocking something!

**Comment by tscholze** [comment]
@MarcelReiter I'll merge the PR because its awesome! But I might "add review comments" in the future to learn more about it if it is okay for you.

**Comment by MarcelReiter** [comment]
> @MarcelReiter[](https://github.com/tscholze) I'll merge the PR because its awesome! But I might "add review comments" in the future to learn more about it if it is okay for you.

Isn't that the whole point of the exercise? 😄

**Pull request merged**
