### PR TITLE
[App] Added custom map icons for crash, misc, roadwork and webcam

### PR DESCRIPTION
**Pull request by tscholze**
re #4

### CODE REVIEW

**Comment by MarcelReiter** [comment]
Is there a reason these drawables are in `drawable-v24`?

Also, if you can, provide a drawable for each resolution (mdpi ... xxxhdpi).

**Comment by tscholze** [comment]
@MarcelReiter hm in Android Studio, I just see "drawables". *hm*

**Comment by tscholze** [comment]
@MarcelReiter I would like to use vectors - but than your fixed Marker does not like me. :'(

**Comment by MarcelReiter** [comment]
>@MarcelReiter hm in Android Studio, I just see "drawables". hm

In android Studio: At the top of the project-folder-tree there is a toggle, which most probably is "Android".
If you change this to Project, you see the real structure

**Pull request merged**
